apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: weather-pod
  template:
    metadata:
      labels:
        name: weather-pod
    spec:
      containers:
      - name: weather-pod
        image: alexeydoom/test-k8s-3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80