apiVersion: v1
kind: Pod
metadata:
  name: weather-pod
  labels:
    name: weather-pod
spec:
  containers:
  - name: weather-pod
    image: alexeydoom/test-k8s-3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80